#!/usr/bin/env python3
"""
Interactive setup wizard for ARIA's .env configuration.
Run: python setup.py
"""

import os
import sys
import questionary
from rich.console import Console
from rich.panel import Panel
from rich.text import Text
from rich.table import Table
from rich.columns import Columns
from rich import box
from questionary import Style

# ─── Styling ──────────────────────────────────────────────────────────

console = Console()

PROMPT_STYLE = Style([
    ("qmark", "fg:#e879f9 bold"),        # purple bullet
    ("question", "fg:#f0f0f0 bold"),      # white question
    ("answer", "fg:#67e8f9 bold"),        # cyan answer
    ("pointer", "fg:#e879f9 bold"),       # purple pointer
    ("highlighted", "fg:#e879f9 bold"),   # purple highlighted
    ("selected", "fg:#67e8f9"),           # cyan selected
    ("instruction", "fg:#737373"),        # gray instructions
])

ENV_PATH = os.path.join(os.path.dirname(__file__), ".env")
ENV_EXAMPLE_PATH = os.path.join(os.path.dirname(__file__), ".env.example")


# ─── Helpers ──────────────────────────────────────────────────────────

def banner():
    """Display a rich banner for the setup wizard."""
    title = Text()
    title.append("╔══════════════════════════════════════╗\n", style="bold magenta")
    title.append("║       ", style="bold magenta")
    title.append("🤖  ARIA Setup Wizard", style="bold white")
    title.append("       ║\n", style="bold magenta")
    title.append("╚══════════════════════════════════════╝", style="bold magenta")
    console.print(title, justify="center")
    console.print()


def section(title: str, description: str = ""):
    """Print a styled section header."""
    console.print()
    console.rule(f"[bold magenta]{title}[/]", style="dim")
    if description:
        console.print(f"  [dim]{description}[/]")
    console.print()


def info(msg: str):
    console.print(f"  [dim cyan]ℹ {msg}[/]")


def success(msg: str):
    console.print(f"  [bold green]✓ {msg}[/]")


def warn(msg: str):
    console.print(f"  [bold yellow]⚠ {msg}[/]")


def ask_text(label: str, default: str = "", instruction: str = "") -> str:
    """Ask a text question with questionary."""
    full = label
    if instruction:
        full += f"  ({instruction})"
    return questionary.text(full, default=default, style=PROMPT_STYLE).ask() or default


def ask_password(label: str, instruction: str = "") -> str:
    """Ask a secret/password."""
    full = label
    if instruction:
        full += f"  ({instruction})"
    return questionary.password(full, style=PROMPT_STYLE).ask() or ""


def ask_select(label: str, choices: list, default: str = None) -> str:
    """Ask the user to select from a list."""
    return questionary.select(label, choices=choices, default=default, style=PROMPT_STYLE).ask()


def ask_confirm(label: str, default: bool = False) -> bool:
    """Ask a yes/no question."""
    return questionary.confirm(label, default=default, style=PROMPT_STYLE).ask()


def load_existing_env() -> dict:
    """Load existing .env values if the file exists."""
    values = {}
    if os.path.exists(ENV_PATH):
        with open(ENV_PATH, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, _, val = line.partition("=")
                    values[key.strip()] = val.strip()
    return values


def write_env(config: dict):
    """Write the final .env file."""
    lines = [
        "# Auto-generated by setup.py",
        "# Edit manually or re-run the wizard to update.",
        "",
    ]

    sections = [
        ("Core I/O", ["INPUT_MODE", "OUTPUT_MODE"]),
        ("Telegram Bot", ["TELEGRAM_BOT_TOKEN"]),
        ("LLM (Brain)", ["AI_SOURCE", "AI_MODEL_ID", "OLLAMA_HOST", "MISTRAL_API_KEY", "KOBOLD_URL", "TEMPERATURE", "TARGET_LANGUAGE"]),
        ("Memory / Context", ["MEMORY_MAX_MESSAGES", "CONTEXT_BACKEND", "CONTEXT_DB_PATH"]),
        ("Tavily Web Search", ["TAVILY_API_KEY", "TAVILY_MAX_RESULTS", "TAVILY_RETURN_METADATA"]),
        ("Speech-to-Text (STT)", ["STT_MODEL", "STT_LANG"]),
        ("Text-to-Speech (TTS)", ["TTS_LANG", "TTS_SPEED", "TTS_OUTPUT_DEVICE", "AUDIO_OUTPUT_DEVICE"]),
        ("HuggingFace", ["HF_TOKEN"]),
        ("Scratchpad", ["SCRATCHPAD_PATH"]),
    ]

    for section_name, keys in sections:
        lines.append(f"# {'=' * 60}")
        lines.append(f"# {section_name}")
        lines.append(f"# {'=' * 60}")
        for key in keys:
            val = config.get(key, "")
            lines.append(f"{key}={val}")
        lines.append("")

    with open(ENV_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")


# ─── Wizard Steps ────────────────────────────────────────────────────

def step_io(config: dict):
    section("Input / Output", "How you talk to ARIA and how she responds.")

    io_mode = ask_select(
        "Local communication mode?",
        choices=[
            questionary.Choice("🎙  Audio (microphone + speakers)", value="audio"),
            questionary.Choice("⌨️  Text (terminal)", value="text"),
        ],
        default="audio",
    )
    config["INPUT_MODE"] = io_mode
    config["OUTPUT_MODE"] = io_mode

    if io_mode == "audio":
        info("Push-to-Talk (Ctrl+Alt) will be enabled with Kokoro voice synthesis.")


def step_telegram(config: dict):
    section("Telegram", "Optional: connect ARIA to a Telegram bot.")

    enable = ask_confirm("Enable the Telegram channel?", default=bool(config.get("TELEGRAM_BOT_TOKEN")))
    if enable:
        token = ask_password("Bot token (from @BotFather)", instruction="leave empty to keep existing")
        if token:
            config["TELEGRAM_BOT_TOKEN"] = token
        if not config.get("TELEGRAM_BOT_TOKEN"):
            warn("No token provided. The Telegram channel will be disabled at launch.")
    else:
        config["TELEGRAM_BOT_TOKEN"] = ""


def step_llm(config: dict):
    section("Artificial Intelligence", "Choose your LLM provider and model.")

    source = ask_select(
        "LLM provider?",
        choices=[
            questionary.Choice("🦙 Ollama (local)", value="ollama"),
            questionary.Choice("🌩  Mistral AI (cloud API)", value="mistral"),
            questionary.Choice("🐉 KoboldAI (local server)", value="kobold"),
        ],
        default=config.get("AI_SOURCE", "ollama"),
    )
    config["AI_SOURCE"] = source

    model_defaults = {
        "ollama": "mistral-nemo:12b",
        "mistral": "mistral-small-latest",
        "kobold": "local-model",
    }
    config["AI_MODEL_ID"] = ask_text(
        "Model identifier?",
        default=config.get("AI_MODEL_ID", model_defaults.get(source, "")),
    )

    if source == "ollama":
        config["OLLAMA_HOST"] = ask_text(
            "Ollama host?",
            default=config.get("OLLAMA_HOST", ""),
            instruction="empty = localhost by default",
        )
    elif source == "mistral":
        key = ask_password("Mistral API key?", instruction="leave empty to keep existing")
        if key:
            config["MISTRAL_API_KEY"] = key
        if not config.get("MISTRAL_API_KEY"):
            warn("No API key provided. Mistral will not work.")
    elif source == "kobold":
        config["KOBOLD_URL"] = ask_text(
            "KoboldAI URL?",
            default=config.get("KOBOLD_URL", "http://localhost:5001/v1"),
        )

    config["TEMPERATURE"] = ask_text(
        "Generation temperature?",
        default=config.get("TEMPERATURE", "0.4"),
        instruction="0.0 = deterministic, 1.0 = creative",
    )

    config["TARGET_LANGUAGE"] = ask_text(
        "Response language?",
        default=config.get("TARGET_LANGUAGE", "English"),
        instruction="e.g. French, English, Spanish...",
    )


def step_memory(config: dict):
    section("Memory & Context", "Conversation persistence and note storage.")

    config["MEMORY_MAX_MESSAGES"] = ask_text(
        "Max messages in LLM context window?",
        default=config.get("MEMORY_MAX_MESSAGES", "20"),
    )

    backend = ask_select(
        "Context persistence backend?",
        choices=[
            questionary.Choice("💨 RAM (volatile, resets on restart)", value="ram"),
            questionary.Choice("💾 SQLite (persistent across sessions)", value="sqlite"),
        ],
        default=config.get("CONTEXT_BACKEND", "ram"),
    )
    config["CONTEXT_BACKEND"] = backend

    if backend == "sqlite":
        config["CONTEXT_DB_PATH"] = ask_text(
            "SQLite database path?",
            default=config.get("CONTEXT_DB_PATH", ".data/context.db"),
        )

    scratchpad = ask_confirm(
        "Enable scratchpad (persistent JSON notes)?",
        default=bool(config.get("SCRATCHPAD_PATH")),
    )
    config["SCRATCHPAD_PATH"] = ask_text(
        "Scratchpad file path?",
        default=config.get("SCRATCHPAD_PATH", ".data/scratchpad.json"),
    ) if scratchpad else ""


def step_stt(config: dict):
    if config.get("INPUT_MODE") != "audio":
        return

    section("Speech-to-Text (STT)", "Faster-Whisper configuration.")

    config["STT_MODEL"] = ask_select(
        "Whisper model size?",
        choices=[
            questionary.Choice("tiny   (ultra fast, less accurate)", value="tiny"),
            questionary.Choice("base   (fast)", value="base"),
            questionary.Choice("small  (balanced)", value="small"),
            questionary.Choice("medium (recommended)", value="medium"),
            questionary.Choice("large  (most accurate, slow)", value="large-v3"),
        ],
        default=config.get("STT_MODEL", "small"),
    )

    config["STT_LANG"] = ask_text(
        "Speech recognition language?",
        default=config.get("STT_LANG", "en"),
        instruction="ISO code: en, fr, es, de...",
    )


def step_tts(config: dict):
    if config.get("OUTPUT_MODE") != "audio":
        return

    section("Text-to-Speech (TTS)", "Kokoro Voice configuration.")

    config["TTS_LANG"] = ask_text(
        "Kokoro language code?",
        default=config.get("TTS_LANG", "a"),
        instruction="a = American English, b = British, f = French, j = Japanese...",
    )

    config["TTS_SPEED"] = ask_text(
        "Speech speed?",
        default=config.get("TTS_SPEED", "1.0"),
        instruction="0.5 = slow, 1.0 = normal, 1.5 = fast",
    )


def step_extras(config: dict):
    section("Extras", "Optional tools (web search, HuggingFace).")

    tavily = ask_confirm(
        "Enable Tavily web search?",
        default=bool(config.get("TAVILY_API_KEY")),
    )
    if tavily:
        key = ask_password("Tavily API key?", instruction="leave empty to keep existing")
        if key:
            config["TAVILY_API_KEY"] = key
        config["TAVILY_MAX_RESULTS"] = config.get("TAVILY_MAX_RESULTS", "4")
        config["TAVILY_RETURN_METADATA"] = config.get("TAVILY_RETURN_METADATA", "true")
    else:
        config["TAVILY_API_KEY"] = ""

    hf = ask_confirm(
        "Do you need a HuggingFace token (private models)?",
        default=bool(config.get("HF_TOKEN")),
    )
    if hf:
        token = ask_password("HuggingFace token?", instruction="leave empty to keep existing")
        if token:
            config["HF_TOKEN"] = token
    else:
        config["HF_TOKEN"] = ""


# ─── Summary ─────────────────────────────────────────────────────────

def display_summary(config: dict):
    """Display a rich summary table of the final configuration."""
    console.print()
    console.rule("[bold magenta]Summary[/]", style="dim")
    console.print()

    # Secrets to mask
    secrets = {"MISTRAL_API_KEY", "TAVILY_API_KEY", "HF_TOKEN", "TELEGRAM_BOT_TOKEN"}

    table = Table(box=box.ROUNDED, border_style="magenta", show_header=True, header_style="bold white")
    table.add_column("Variable", style="cyan", min_width=25)
    table.add_column("Value", style="white", min_width=35)

    for key, val in config.items():
        display_val = val
        if key in secrets and val:
            display_val = val[:4] + "•" * (len(val) - 4)
        if not display_val:
            display_val = "[dim]—[/dim]"
        table.add_row(key, display_val)

    console.print(table)
    console.print()


# ─── Main ────────────────────────────────────────────────────────────

def main():
    banner()

    if os.path.exists(ENV_PATH):
        info(f"Existing .env file detected ({ENV_PATH}).")
        overwrite = ask_confirm("Update existing configuration?", default=True)
        if not overwrite:
            console.print("  [dim]Cancelled.[/]")
            sys.exit(0)

    config = load_existing_env()

    try:
        step_io(config)
        step_telegram(config)
        step_llm(config)
        step_memory(config)
        step_stt(config)
        step_tts(config)
        step_extras(config)
    except KeyboardInterrupt:
        console.print("\n  [bold red]Cancelled by user.[/]")
        sys.exit(1)

    display_summary(config)

    confirm = ask_confirm("Write this configuration to .env?", default=True)
    if confirm:
        write_env(config)
        success(f".env file written to {ENV_PATH}")
        console.print()
        console.print(Panel(
            "[bold white]You can now launch ARIA:[/]\n\n"
            "  [bold cyan]python core.py[/]\n",
            border_style="green",
            title="🚀 Ready",
            title_align="left",
        ))
    else:
        warn("No file was written.")


if __name__ == "__main__":
    main()
